spring:
  application:
    name: razorpay
  datasource:
    url: jdbc:postgresql://localhost:5432/razorpayDB
    username: postgres
    password: 122003
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
payment:
  simulator:
    poll-interval-ms: 5000
    chaos-mode: NORMAL
    method:
      CARD:
        min-delay-seconds: 2
        max-delay-second: 6
        success-rate: 90
      UPI:
        min-delay-seconds: 1
        max-delay-second: 3
        success-rate: 95
      NET_BANKING:
        min-delay-seconds: 4
        max-delay-second: 10
        success-rate: 80
jwt:
  secret-key: ebogshnfoieofleofjoseejfoiejofwofwefnsfesf
